name: Ezaz GitHub Action CI Pipeline1

# on: [push, pull_request]
on:
  workflow_dispatch:


permissions:
  id-token: write
  contents: read
  
jobs:
  Test-job-1:
    runs-on: ubuntu-22.04
    steps:
      - name: Checckout step
        uses: actions/checkout@v7.0.0
      
      - name: Good Morning Greetings
        run: echo Hello Honey, Good Morning ..!

      - name: Linux Commands
        run: |
          ls
          pwd
          whoami

  Test-job-2:
    runs-on: ubuntu-latest

    steps: 
    - name: Checckout step
      uses: actions/checkout@v7.0.0
      
    - name: Good Night Greetings
      run: echo Hello Baby, Good Night ..!
  
  Test-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId":"${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId":"${{ secrets.AZURE_TENANT_ID }}"
            }

      - run: az login

    
        
 


      



