name: Ezaz GitHub Action CI Pipeline-29.6.2026

on: [push]
# on:
#   workflow_dispatch:


permissions:
  id-token: write
  contents: read
  
jobs:
  Test-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      
      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Commands
        run: |
          terraform init
          terraform validate
          terraform import azurerm_resource_group.rg "/subscriptions/ddece533-2a97-4b73-8056-67abfc878c00/resourceGroups/Ezaz-GitHubAction-rg"
          terraform plan
          terraform apply --auto-approve